version: "3"
services:
  web:
    build:
      context: . # Look in current directory for docker-compose.yml
      dockerfile: Dockerfile.dev # Use this Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]